---
- name: Compress a folder /web to archive opt.zip
  hosts: web1
  tasks:
    - archive:
        path: /opt/web
        dest: /root/opt.zip
        format: zip

- name: Compress multiple files
  hosts: web1
  tasks:
    - archive:
        path:
          - /root/file1.txt
          - /usr/local/share/file2.txt
          - /var/log/lastlog
        dest: /root/files.tar.bz2
        format: bz2

    - name: Archive folder /opt to /root/opt.zip
      archive:
        path:
          - /opt
        dest: /root/opt.zip
        format: zip