---
- hosts: all
  become: yes
  tasks:
    - name: Create devops user
      user:
        name: devops
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ 'password' | password_hash('sha512') }}"

    - name: Add devops user to sudoers
      copy:
        dest: "/etc/sudoers.d/devops"
        content: "devops  ALL=(ALL) NOPASSWD: ALL"

    - name: Deploy ssh key
      authorized_key:
        user: devops
        key: "{{ lookup('file', '/tmp/devops.pub') }}"
        state: present

    - name: Set all authorized keys
      authorized_key:
        user: root
        key: "{{ item }}"
        state: present
        exclusive: yes
      with_file:
        - public_keys/my-keys