---
- name: Create a cron job to clear last log
  hosts: node00
  tasks:
    - name: Create cron job
      cron:
        name: "Clear lastlog"
        minute: "0"
        hour: "0"
        job: echo "" > /var/log/lastlog

    - name: Create cron job
      cron:
        name: "Free Memory Check"
        minute: "0"
        hour: "*/2"
        job: "sh /root/free.sh"

- name: Remove cron job from node00
  hosts: node00
  tasks:
    - name: Remove cron jobu
      cron:
        name: "Check memory"
        state: absent

---
- name: Cleanup /tmp after every reboot
  hosts: node00
  tasks:
    - cron:
        name: cleanup
        job: rm -rf /tmp/*
        special_time: reboot

---
- name: Create cron job for yum
  hosts: node00
  gather_facts: no
  tasks:
    - name: Create a cron
      cron:
        name: yum update
        weeekday: 0
        minute: 5
        hour: 8
        user: root
        job: "yum -y update"
        cron_file: ansible_yum