---
- name: Print hello message
  hosts: all
  gather_facts: no  # don't show ansible facts or use gathering = explicit in ansible.cfg
  tasks:
    - debug:
        var: ansible_facts  # show all ansible facts