---
- hosts: web1
  tasks:
    - name: create file perm.txt
      file: path=/opt/data/perm.txt mode=0640 state=touch
~                                                                                                  
~      