---
- hosts: web1
  tasks:
    - firewalld:
        source: 172.20.1.101
        state: eneabled
        zone: internal
        permanent: yes
        immediate: yes

---
- hosts: web1
  tasks:
    - firewalld:
        port: 161/udp
        zone: block
        permanent: yes
        immediate: yes
        state: enabled

---
- hosts: web1
  tasks:
    - name: Enable HTTPS
      firewalld:
        source: 172.20.1.2
        service: https
        zone: internal
        state: enabled
        permanent: yes

    - service:
        name: firewalld
        state: reloaded
~                                 