-
  name: Play 1
  hosts: web
  tasks:
    - name: Search line in file and replace it or add it if doesn't exist
      lineinfile:
        path: /etc/resolf.conf
        line: 'nameserver 10.1.250.10'
