---
- name: Install pkgs on CentOS
  hosts: web1
  tasks:
    - name: Install web on CentOS
      yum: name=httpd state=installed
    - name: Install latest version of sudo
      yum: name=sudo state=latest
    - name: Downgrade version of vsftpd
      yum: name=vsftpd-2.2.2 state=present allow_downgrade=yes

- name: Install web on Ubuntu
  hosts: web2
  tasks:
    - apt: name=apache2 state=installed

- name: Install web on any host
  hosts: all
  tasks:
    - package: name=httpd state=installed