---
- name: Extract local.zip to web1
  hosts: web1
  tasks:
    - unarchive:
        src: local.zip
        dest: /tmp
    - unarchive:
        src: /root/data.tar.gz
        dest: /srv
        remote_src: yes
    - file: 
        path: /root/data.tar.gz
        state: absent

- name: Download & extract from url
  hosts: web1
  tasks:
    - unarchive:
        src: https://github.com/kodekloudhub/Hello-World/archive/master.zip
        dest: /root
        remote_src: yes

  