---

- hosts: web
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone 
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
        user: simone
        state: present
        key: ""

  - name: add sudoers file for simone
    tags: always
    copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440

  - name: create group admin
    group: name='admin' state=present

  - name: create user admin 
    user: name='admin' uid=2048 group='admin'

  ---
- hosts: all
  tasks:
    - user: name='admin' state=absent
    - group: name='admin' state=absent