- name: Check status of service and email if its down
  hosts: web
  tasks:
    - command: service httpd status
      register: result

    - mail:
        to: admin@company.com
        subject: Service alert
        body: Httpd Service is down
        when: result.stdout.find('down') != -1
