---

- hosts: all
  become: true
  tasks:

  - name: install apache&php packages
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
