---

- hosts: web
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone 
      groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
        user: simone
        key: ""

  - name: add sudoers file for simone
    tags: always
    copy:
        src: sudoer_simone
        dest: /etc/sudoers.d/simone
        owner: root
        group: root
        mode: 0440
