- name: Deploy web apps
  hosts: server1, server2, server3, server4, server5
  serial: 3 # use default linear strategy for 3 servers at once
  tasks:
    - name: Install dependencies
      << code hidden >>
    - name: Install MySQL DB
      << code hidden >>
    - name: Start MySQL service
      << code hidden >>
    - name: Install Flask dependencies
      << code hidden >>
    - name: Run web-server
      << code hidden >>