- name: Deploy web apps
  hosts: server1, server2, server3
  strategy: free
  tasks:
    - name: Install dependencies
      << code hidden >>
    - name: Install MySQL DB
      << code hidden >>
    - name: Start MySQL service
      << code hidden >>
    - name: Install Flask dependencies
      << code hidden >>
    - name: Run web-server
      << code hidden >>