---
- hosts: all
  tasks:
    - name: Install and configure httpd web server
      block:
        - yum: name=httpd state=present
        - service: name=httpd state=started
      when: ansible_facts['distribution'] == 'CentOS'
      
      rescue:
        - debug: msg="Playbook has failed for {{ inventory_hostname }} node"