---
- hosts: node02
  tasks:
    - name: Start nginx
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - nginx
        - mariadb

    - name: Clean nginx document
      shell: rm -rf /usr/share/nginx/html/*

    - name: Download zip
      unarchive:
        src: https://github.com/indercodes/ansible-1100-mock-nginx/raw/master/index.php.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Update DB
      replace:
        path: /usr/share/nginx/html/index.php
        regexp: '{{ item.1 }}'
        replace: '{{ item.2 }}'
      with_items:
        - {1: '\$database.*', 2: '$database = "mydb";' }
        - {1: '\$username.*', 2: '$username = "myuser";' }
        - {1: '\$password.*', 2: '$password = "mypassword";' }

    - name: Restart nginx
      service:
        name: nginx
        state: restarted