- name: Install MariaDB
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: installed

- name: Create mysql config
  template: src=templates/my.cnf.j2 dest=/etc/my.cnf

- name: Start mariadb service
  service: name=mariadb state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Add firewalld rules
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create DB
  mysql_db: name={{ dbname }} state=present

- name: gather facts from lampweb
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ hostvars[groups['web_servers'][0]].groups.web_servers }}"

- name: Create Application DB User
  tags: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host={{ hostvars['lampweb']['ansible_facts']['eth0']['ipv4']['address'] }} state=present

- name: Move populate script to db host
  template: src=templates/db-load-script.sql.j2 dest=/tmp/db-load-script.sql

- name: Populate DB
  shell: mysql -f < /tmp/db-load-script.sql
