- name: Deploy web apps
  hosts: server1, server2, server3
  any_errors_fatal: true
  tasks:
    - name: Install dependencies
      << code hidden >>
    - name: Install MySQL DB
      << code hidden >>
    - name: Start MySQL service
      << code hidden >>
    - name: Install Flask dependencies
      << code hidden >>
    - name: Run web-server
      << code hidden >>

    - command: cat /var/log/server.log
      register: command_output
      failed_when: '"ERROR" in command_output.stdout'