- name: Install httpd php
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: Install git
  yum: name=git state=installed

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: Add firewalld rules
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: Set index.php as default page
  tags: "Set index.php as the default page"
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'DirectoryIndex index.html'
    replace: 'DirectoryIndex index.php'

- name: Start httpd service
  service: name=httpd state=started enabled=yes
    
- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/  force=yes

- name: Creates the index.php file
  template: src=templates/index.php.j2 dest=/var/www/html/index.php