---
- name: Deploy lamp stack apps
  hosts: all
  become: yes
  tasks:
    - include_tasks: tasks/common.yml 

- name: Deploy db on db-servers
  hosts: lamp-db
  become: yes
  tasks:
    - include_tasks: tasks/db.yml

- name: Deploy on web-servers
  hosts: lampweb
  become: yes
  tasks:
    - include_tasks: tasks/web.yml