---
- name: Check /etc/hosts file
  hosts: all
  tasks:
    - shell: cat /etc/hosts
      register: result  # execute a task and save returned value in a variable to use in the task later

    - debug:
      var: result.stdout  # result.stdout/result.stderr.result.rc

- name: Play2
  hosts: all
  tasks:
    - debug:
      var: result.rc