---
- hosts: all
  gather_facts: no
  tasks:
    - name: stat module help to find the file info
      stat:
        path: /var/run
      register: your_variable

    # for your reference, check the outputs of these
    - debug: var=your_variable.stat

    # your code goes here...
    - shell: echo "{{your_variable.stat}}" > /tmp/by_ansible


---
- name: help me fix it playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: alternative way to gather facts about remote host
      setup: filter='ansible_dist*'
      register: facts
 
    - debug: var=facts.ansible_facts.ansible_distribution

    - shell: echo "{{facts.ansible_facts.ansible_distribution}}" > /tmp/output.txt