---
- hosts: web2
  tasks:
    - shell: git --version
      register: check_if_git_installed
      ignore_errors: true

    - debug: var=check_if_git_installed
    
    - shell: echo 'Oops, git is missing' > /tmp/is_git_installed.txt
      when: check_if_git_installed.rc != 0

    #- shell: dpkg -l git
    #  register: check_if_git_installed
                                             