-
  name: Create users
  hosts: localhost
  tasks:
    - user: name='{{ item }}' state=present
      loop:
        - john
        - james
        - john
        - jane
        - joane
        - jim
        - jason
        - jack
        - joe
    - user: name='{{ item.name }}' state=present uid='{{ item.uid }}''
      loop:
        - name: jess
          uid: 1010
        - { name: jose, uid: 1020 }